name: build

on:
    push:
        branches:
            - c++

jobs:
    build_unix:
        runs-on: ubuntu-latest
        name: Compile
        steps:
            - uses: actions/checkout@v3
            - run: make
